import type { ProjectGraph } from "@/lib/types/assembler"

// Golden 예시 3 — 음식 배달 주문. 메뉴 → 장바구니 → 주문완료 3화면.
// 담기 안내(toast)·수량/합계 갱신(stateChange)·주문완료 이동(navigate) 등 result.kind 시연.
// stores/menu_items/orders 3개 전역 DB가 Feature·Api·Element 전반에 공유된다.

export const FOOD_DELIVERY: { idea: string; graph: ProjectGraph } = {
  idea: "음식 배달 주문 앱. 가게 메뉴를 보고 담은 다음, 장바구니에서 수량을 조절하고 주문하면 주문 완료 화면으로 넘어가게 해줘.",
  graph: {
    id: "food-delivery",
    name: "음식 배달 주문",
    description: "메뉴를 담아 장바구니에서 주문하고 완료 화면으로 넘어가는 배달 주문 앱.",

    requirements: [
      {
        id: "req-order-food",
        title: "사용자는 메뉴를 담아 주문할 수 있어야 한다.",
        description: "가게 메뉴를 장바구니에 담고 수량을 조절한 뒤 한 번에 주문한다.",
      },
    ],

    features: [
      {
        id: "feat-menu-browse",
        name: "Menu Browse",
        description: "가게 메뉴 조회 및 장바구니 담기.",
        businessRules: [
          "품절 메뉴는 담기 버튼을 비활성화한다.",
          "담기 시 장바구니 수량 배지를 갱신한다.",
        ],
        requirementIds: ["req-order-food"],
        pageIds: ["page-menu"],
        apiIds: ["api-list-menu", "api-add-cart"],
        databaseIds: ["db-stores", "db-menu-items", "db-carts"],
        requiredData: [],
        optionalData: ["수량"],
      },
      {
        id: "feat-cart-order",
        name: "Cart Order",
        description: "장바구니 수량 조절 및 주문 생성.",
        businessRules: [
          "최소 주문 금액 미만이면 주문할 수 없다.",
          "주문 성공 시 주문 완료 화면으로 이동한다.",
        ],
        requirementIds: ["req-order-food"],
        pageIds: ["page-cart", "page-order-done"],
        apiIds: ["api-update-cart", "api-place-order"],
        databaseIds: ["db-carts", "db-orders"],
        requiredData: ["배송 주소", "결제 수단"],
        optionalData: ["요청 사항"],
      },
    ],

    pages: [
      {
        id: "page-menu",
        name: "Menu",
        description: "가게 메뉴 목록과 담기 버튼을 보여주는 화면.",
        featureIds: ["feat-menu-browse"],
        wireframeId: "wf-menu",
        pageFlowId: "flow-menu",
        apiIds: ["api-list-menu", "api-add-cart"],
        databaseIds: ["db-stores", "db-menu-items", "db-carts"],
        x: 40,
        y: 40,
        device: "mobile",
      },
      {
        id: "page-cart",
        name: "Cart",
        description: "담은 메뉴의 수량을 조절하고 주문하는 화면.",
        featureIds: ["feat-cart-order"],
        wireframeId: "wf-cart",
        apiIds: ["api-update-cart", "api-place-order"],
        databaseIds: ["db-carts", "db-orders"],
        x: 460,
        y: 40,
        device: "mobile",
      },
      {
        id: "page-order-done",
        name: "Order Done",
        description: "주문 접수 결과를 보여주는 완료 화면.",
        featureIds: ["feat-cart-order"],
        wireframeId: "wf-order-done",
        apiIds: [],
        databaseIds: ["db-orders"],
        x: 880,
        y: 40,
        device: "mobile",
      },
    ],

    wireframes: [
      {
        id: "wf-menu",
        pageId: "page-menu",
        uiElementIds: ["el-store-name", "el-menu-item", "el-add-cart-button", "el-go-cart-button"],
      },
      {
        id: "wf-cart",
        pageId: "page-cart",
        uiElementIds: ["el-cart-qty", "el-cart-total", "el-place-order-button"],
      },
      {
        id: "wf-order-done",
        pageId: "page-order-done",
        uiElementIds: ["el-done-heading", "el-done-status"],
      },
    ],

    uiElements: [
      {
        id: "el-store-name",
        name: "Store Heading",
        description: "가게 이름 표시.",
        type: "heading",
        props: { text: "행복분식" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: ["api-list-menu"],
        databaseIds: ["db-stores"],
        result: { kind: "none" },
      },
      {
        id: "el-menu-item",
        name: "Menu Item",
        description: "메뉴 한 건 표시 — 장식 요소.",
        type: "text",
        props: { text: "떡볶이 · 4,000원" },
        states: [
          { label: "Default" },
          { label: "Disabled", detail: "품절 메뉴는 흐리게" },
        ],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-add-cart-button",
        name: "Add To Cart Button",
        description: "선택한 메뉴를 장바구니에 담는다.",
        type: "button",
        props: { label: "담기", variant: "primary" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "담는 중" },
          { label: "Disabled", detail: "품절 메뉴일 때" },
        ],
        action: "Click",
        apiIds: ["api-add-cart"],
        databaseIds: ["db-carts", "db-menu-items"],
        result: { kind: "toast", detail: "장바구니에 담았어요 안내 노출" },
      },
      {
        id: "el-go-cart-button",
        name: "Go To Cart Button",
        description: "장바구니 화면으로 이동한다.",
        type: "button",
        props: { label: "장바구니 보기", variant: "solid" },
        states: [
          { label: "Default" },
          { label: "Disabled", detail: "장바구니가 비었을 때" },
        ],
        action: "Click",
        apiIds: [],
        databaseIds: [],
        result: { kind: "navigate", toPageId: "page-cart", detail: "장바구니 화면으로 이동" },
      },
      {
        id: "el-cart-qty",
        name: "Quantity Stepper",
        description: "담은 메뉴의 수량을 조절한다.",
        type: "number-stepper",
        props: { value: 1 },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "수량 저장 중" },
        ],
        action: "Change",
        apiIds: ["api-update-cart"],
        databaseIds: ["db-carts"],
        result: { kind: "stateChange", detail: "수량과 합계 금액 갱신" },
      },
      {
        id: "el-cart-total",
        name: "Total Badge",
        description: "주문 합계 금액 표시 — 장식 요소.",
        type: "badge",
        props: { text: "8,000원", status: "neutral" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-place-order-button",
        name: "Place Order Button",
        description: "장바구니 내용으로 주문을 생성하고 완료 화면으로 이동한다.",
        type: "button",
        props: { label: "주문하기", variant: "solid" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "주문 접수 중 비활성" },
          { label: "Disabled", detail: "최소 주문 금액 미만일 때" },
        ],
        action: "Click",
        apiIds: ["api-place-order"],
        databaseIds: ["db-orders", "db-carts"],
        result: { kind: "navigate", toPageId: "page-order-done", detail: "주문 성공 시 완료 화면으로" },
      },
      {
        id: "el-done-heading",
        name: "Done Heading",
        description: "주문 완료 안내 제목 — 장식 요소.",
        type: "heading",
        props: { text: "주문이 접수됐어요" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-done-status",
        name: "Order Status Badge",
        description: "주문 상태 표시.",
        type: "badge",
        props: { text: "조리 중", status: "positive" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "상태 불러오는 중" },
        ],
        action: "",
        apiIds: [],
        databaseIds: ["db-orders"],
        result: { kind: "none" },
      },
    ],

    apis: [
      {
        id: "api-list-menu",
        method: "GET",
        path: "/stores/:id/menu",
        purpose: "가게의 메뉴 목록과 품절 여부를 조회한다.",
        databaseIds: ["db-stores", "db-menu-items"],
        success: "Menu List Returned",
        error: "조회 실패 — 일시적인 오류 안내",
      },
      {
        id: "api-add-cart",
        method: "POST",
        path: "/carts/items",
        purpose: "선택한 메뉴를 장바구니에 담는다.",
        databaseIds: ["db-carts", "db-menu-items"],
        success: "Cart Item Added",
        error: "품절 — 담기 불가 안내",
      },
      {
        id: "api-update-cart",
        method: "PATCH",
        path: "/carts/items/:id",
        purpose: "장바구니 항목의 수량을 변경한다.",
        databaseIds: ["db-carts"],
        success: "Cart Item Updated",
        error: "저장 실패 — 잠시 후 다시 시도 안내",
      },
      {
        id: "api-place-order",
        method: "POST",
        path: "/orders",
        purpose: "장바구니 내용으로 주문을 생성한다.",
        databaseIds: ["db-orders", "db-carts"],
        success: "Order Created",
        error: "최소 주문 금액 미만 — 인라인 에러 노출",
      },
    ],

    databases: [
      {
        id: "db-stores",
        name: "stores",
        purpose: "가게 정보 저장.",
        columns: [
          "name — 가게 이름",
          "min_order_amount — 최소 주문 금액",
        ],
      },
      {
        id: "db-menu-items",
        name: "menu_items",
        purpose: "가게 메뉴 항목 저장.",
        columns: [
          "store_id — 소속 가게",
          "name — 메뉴 이름",
          "price — 가격",
          "is_sold_out — 품절 여부",
        ],
      },
      {
        id: "db-carts",
        name: "carts",
        purpose: "사용자 장바구니 항목 저장.",
        columns: [
          "menu_item_id — 담은 메뉴",
          "quantity — 수량",
        ],
      },
      {
        id: "db-orders",
        name: "orders",
        purpose: "접수된 주문 저장.",
        columns: [
          "total_amount — 주문 합계 금액",
          "status — 주문 상태",
          "created_at — 주문 시각",
        ],
      },
    ],

    pageFlows: [
      {
        id: "flow-menu",
        pageId: "page-menu",
        steps: [
          { id: "step-menu-enter", label: "메뉴 화면 진입", nextStepIds: ["step-menu-add"] },
          { id: "step-menu-add", label: "메뉴 담기", nextStepIds: ["step-menu-go-cart"] },
          { id: "step-menu-go-cart", label: "장바구니로 이동", nextStepIds: [] },
        ],
      },
    ],

    userFlow: {
      id: "userflow-delivery",
      edges: [
        {
          id: "edge-menu-to-cart",
          fromPageId: "page-menu",
          toPageId: "page-cart",
          triggerElementId: "el-go-cart-button",
          condition: "장바구니 보기를 누를 때",
        },
        {
          id: "edge-cart-to-done",
          fromPageId: "page-cart",
          toPageId: "page-order-done",
          triggerElementId: "el-place-order-button",
          condition: "주문 성공 시",
        },
      ],
    },
  },
}
