import type { ProjectGraph } from "@/lib/types/assembler"

// Golden 예시 4 — 헬스장 클래스 예약. 클래스 목록 → 예약 → 내 예약 3화면.
// 정원 초과 시 inlineError, 예약 취소 시 stateChange 등 result.kind 다양화.
// device를 tablet로 둬(키오스크 가정) 디바이스 다양성 시연.

export const GYM_BOOKING: { idea: string; graph: ProjectGraph } = {
  idea: "헬스장 그룹 클래스 예약 키오스크. 오늘 클래스 목록을 보고, 클래스를 골라 예약하고, 내 예약 목록에서 취소할 수 있어야 해.",
  graph: {
    id: "gym-booking",
    name: "헬스장 클래스 예약",
    description: "그룹 클래스를 둘러보고 예약하며 내 예약을 취소하는 키오스크 앱.",

    requirements: [
      {
        id: "req-book-class",
        title: "회원은 그룹 클래스를 예약하고 취소할 수 있어야 한다.",
        description: "오늘 클래스 목록에서 클래스를 골라 예약하고, 내 예약 화면에서 취소한다.",
      },
    ],

    features: [
      {
        id: "feat-class-browse",
        name: "Class Browse",
        description: "오늘 클래스 목록 조회 및 예약 진입.",
        businessRules: [
          "정원이 찬 클래스는 예약 버튼을 비활성화한다.",
          "지난 시간 클래스는 목록에서 제외한다.",
        ],
        requirementIds: ["req-book-class"],
        pageIds: ["page-class-list", "page-class-book"],
        apiIds: ["api-list-classes", "api-get-class"],
        databaseIds: ["db-classes"],
        requiredData: [],
        optionalData: [],
      },
      {
        id: "feat-booking-manage",
        name: "Booking Manage",
        description: "클래스 예약 생성 및 내 예약 취소.",
        businessRules: [
          "예약은 회원당 시간대별 1건만 가능하다.",
          "클래스 시작 1시간 전까지만 취소할 수 있다.",
        ],
        requirementIds: ["req-book-class"],
        pageIds: ["page-class-book", "page-my-bookings"],
        apiIds: ["api-create-booking", "api-cancel-booking"],
        databaseIds: ["db-classes", "db-bookings"],
        requiredData: ["클래스 시간대"],
        optionalData: [],
      },
    ],

    pages: [
      {
        id: "page-class-list",
        name: "Class List",
        description: "오늘 그룹 클래스 목록을 보여주는 화면.",
        featureIds: ["feat-class-browse"],
        wireframeId: "wf-class-list",
        pageFlowId: "flow-class-list",
        apiIds: ["api-list-classes"],
        databaseIds: ["db-classes"],
        x: 40,
        y: 40,
        device: "tablet",
      },
      {
        id: "page-class-book",
        name: "Class Book",
        description: "선택한 클래스 정보를 확인하고 예약하는 화면.",
        featureIds: ["feat-class-browse", "feat-booking-manage"],
        wireframeId: "wf-class-book",
        apiIds: ["api-get-class", "api-create-booking"],
        databaseIds: ["db-classes", "db-bookings"],
        x: 460,
        y: 40,
        device: "tablet",
      },
      {
        id: "page-my-bookings",
        name: "My Bookings",
        description: "내 예약 목록과 취소 버튼을 보여주는 화면.",
        featureIds: ["feat-booking-manage"],
        wireframeId: "wf-my-bookings",
        apiIds: ["api-cancel-booking"],
        databaseIds: ["db-bookings"],
        x: 880,
        y: 40,
        device: "tablet",
      },
    ],

    wireframes: [
      {
        id: "wf-class-list",
        pageId: "page-class-list",
        uiElementIds: ["el-list-heading", "el-class-card", "el-my-bookings-button"],
      },
      {
        id: "wf-class-book",
        pageId: "page-class-book",
        uiElementIds: ["el-book-title", "el-book-time", "el-seats-left", "el-book-button"],
      },
      {
        id: "wf-my-bookings",
        pageId: "page-my-bookings",
        uiElementIds: ["el-bookings-heading", "el-booking-row", "el-cancel-button", "el-bookings-empty"],
      },
    ],

    uiElements: [
      {
        id: "el-list-heading",
        name: "List Heading",
        description: "클래스 목록 제목 — 장식 요소.",
        type: "heading",
        props: { text: "오늘의 클래스" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-class-card",
        name: "Class Card",
        description: "클래스 한 건. 누르면 예약 화면으로 이동한다.",
        type: "text",
        props: { text: "필라테스 · 오전 10시" },
        states: [
          { label: "Default" },
          { label: "Disabled", detail: "정원이 찬 클래스는 흐리게" },
        ],
        action: "Click",
        apiIds: ["api-list-classes"],
        databaseIds: ["db-classes"],
        result: { kind: "navigate", toPageId: "page-class-book", detail: "선택한 클래스 예약 화면으로" },
      },
      {
        id: "el-my-bookings-button",
        name: "My Bookings Button",
        description: "내 예약 목록 화면으로 이동한다.",
        type: "button",
        props: { label: "내 예약 보기", variant: "primary" },
        states: [{ label: "Default" }],
        action: "Click",
        apiIds: [],
        databaseIds: [],
        result: { kind: "navigate", toPageId: "page-my-bookings", detail: "내 예약 화면으로 이동" },
      },
      {
        id: "el-book-title",
        name: "Class Title",
        description: "클래스 이름 표시.",
        type: "heading",
        props: { text: "필라테스" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: ["api-get-class"],
        databaseIds: ["db-classes"],
        result: { kind: "none" },
      },
      {
        id: "el-book-time",
        name: "Class Time",
        description: "클래스 시작 시간 표시 — 장식 요소.",
        type: "text",
        props: { text: "오전 10시 시작" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-seats-left",
        name: "Seats Badge",
        description: "남은 자리 수 표시.",
        type: "badge",
        props: { text: "잔여 3석", status: "warning" },
        states: [
          { label: "Default" },
          { label: "Negative", detail: "정원이 찼을 때" },
        ],
        action: "",
        apiIds: [],
        databaseIds: ["db-classes"],
        result: { kind: "none" },
      },
      {
        id: "el-book-button",
        name: "Book Button",
        description: "선택한 클래스를 예약한다.",
        type: "button",
        props: { label: "예약하기", variant: "solid" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "예약 접수 중 비활성" },
          { label: "Disabled", detail: "정원이 찼을 때" },
        ],
        action: "Click",
        apiIds: ["api-create-booking"],
        databaseIds: ["db-bookings", "db-classes"],
        result: { kind: "navigate", toPageId: "page-my-bookings", detail: "예약 접수 후 내 예약으로 이동" },
      },
      {
        id: "el-bookings-heading",
        name: "Bookings Heading",
        description: "내 예약 목록 제목 — 장식 요소.",
        type: "heading",
        props: { text: "내 예약" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-booking-row",
        name: "Booking Row",
        description: "예약 한 건 표시 — 장식 요소.",
        type: "text",
        props: { text: "필라테스 · 오전 10시" },
        states: [
          { label: "Default" },
          { label: "Empty", detail: "예약이 없으면 미노출" },
        ],
        action: "",
        apiIds: ["api-cancel-booking"],
        databaseIds: ["db-bookings"],
        result: { kind: "none" },
      },
      {
        id: "el-cancel-button",
        name: "Cancel Button",
        description: "선택한 예약을 취소한다.",
        type: "button",
        props: { label: "취소하기", variant: "danger" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "취소 처리 중" },
          { label: "Disabled", detail: "시작 1시간 전 지났을 때" },
        ],
        action: "Click",
        apiIds: ["api-cancel-booking"],
        databaseIds: ["db-bookings", "db-classes"],
        result: { kind: "stateChange", detail: "예약 취소 후 목록에서 제거" },
      },
      {
        id: "el-bookings-empty",
        name: "Bookings Empty Hint",
        description: "예약이 없을 때 안내 문구 — 장식 요소.",
        type: "text",
        props: { text: "아직 예약한 클래스가 없어요. 클래스를 예약해 보세요." },
        states: [
          { label: "Default" },
          { label: "Empty", detail: "예약 목록이 비었을 때만 노출" },
        ],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
    ],

    apis: [
      {
        id: "api-list-classes",
        method: "GET",
        path: "/classes",
        purpose: "오늘 진행하는 그룹 클래스 목록을 조회한다.",
        databaseIds: ["db-classes"],
        success: "Class List Returned",
        error: "조회 실패 — 일시적인 오류 안내",
      },
      {
        id: "api-get-class",
        method: "GET",
        path: "/classes/:id",
        purpose: "선택한 클래스의 정원·잔여 자리를 조회한다.",
        databaseIds: ["db-classes"],
        success: "Class Detail Returned",
        error: "클래스 없음 — 마감된 클래스 안내",
      },
      {
        id: "api-create-booking",
        method: "POST",
        path: "/bookings",
        purpose: "선택한 클래스에 예약을 생성한다.",
        databaseIds: ["db-bookings", "db-classes"],
        success: "Booking Created",
        error: "정원 초과 — 인라인 에러 노출",
      },
      {
        id: "api-cancel-booking",
        method: "DELETE",
        path: "/bookings/:id",
        purpose: "내 예약을 취소한다.",
        databaseIds: ["db-bookings", "db-classes"],
        success: "Booking Canceled",
        error: "취소 마감 — 취소 불가 안내",
      },
    ],

    databases: [
      {
        id: "db-classes",
        name: "classes",
        purpose: "그룹 클래스 일정·정원 저장.",
        columns: [
          "name — 클래스 이름",
          "start_at — 시작 시각",
          "capacity — 정원",
          "booked_count — 예약 인원",
        ],
      },
      {
        id: "db-bookings",
        name: "bookings",
        purpose: "회원 예약 내역 저장.",
        columns: [
          "class_id — 예약한 클래스",
          "member_id — 예약한 회원",
          "status — 예약·취소 상태",
        ],
      },
    ],

    pageFlows: [
      {
        id: "flow-class-list",
        pageId: "page-class-list",
        steps: [
          { id: "step-class-enter", label: "클래스 목록 진입", nextStepIds: ["step-class-pick"] },
          { id: "step-class-pick", label: "클래스 선택 또는 내 예약 진입", nextStepIds: ["step-class-navigate"] },
          { id: "step-class-navigate", label: "예약 또는 내 예약 화면으로 이동", nextStepIds: [] },
        ],
      },
    ],

    userFlow: {
      id: "userflow-gym",
      edges: [
        {
          id: "edge-class-to-book",
          fromPageId: "page-class-list",
          toPageId: "page-class-book",
          triggerElementId: "el-class-card",
          condition: "클래스를 선택할 때",
        },
        {
          id: "edge-list-to-bookings",
          fromPageId: "page-class-list",
          toPageId: "page-my-bookings",
          triggerElementId: "el-my-bookings-button",
          condition: "내 예약 보기를 누를 때",
        },
        {
          id: "edge-book-to-bookings",
          fromPageId: "page-class-book",
          toPageId: "page-my-bookings",
          triggerElementId: "el-book-button",
          condition: "예약이 접수됐을 때",
        },
      ],
    },
  },
}
