import type { ProjectGraph } from "@/lib/types/assembler"

// Golden 예시 2 — 동네 중고거래 마켓. 목록 → 상세 → 등록 3화면.
// 상세에서 등록 화면으로 이동하지는 않으나, 목록↔상세, 목록↔등록 navigate edge 정합.
// 전역 공유 객체(db-listings)를 여러 Feature/Page가 참조 — 공유 객체 패턴 시연.

export const USED_MARKET: { idea: string; graph: ProjectGraph } = {
  idea: "동네 중고거래 마켓 앱. 판매 글 목록을 보고, 글을 눌러 상세를 확인하고, 직접 물건을 등록할 수 있어야 해. 상세에서 판매자에게 채팅을 걸 수 있으면 좋겠어.",
  graph: {
    id: "used-market",
    name: "동네 중고거래 마켓",
    description: "판매 글을 둘러보고 상세를 확인하며 직접 물건을 등록하는 중고거래 앱.",

    requirements: [
      {
        id: "req-browse-listing",
        title: "사용자는 판매 글을 탐색하고 상세를 확인할 수 있어야 한다.",
        description: "목록에서 판매 글을 보고, 글을 눌러 상세 정보와 판매자 연락 수단을 확인한다.",
      },
      {
        id: "req-create-listing",
        title: "사용자는 직접 물건을 등록해 판매할 수 있어야 한다.",
        description: "제목·가격·설명을 입력해 새 판매 글을 만든다.",
      },
    ],

    features: [
      {
        id: "feat-listing-browse",
        name: "Listing Browse",
        description: "판매 글 목록 조회 및 상세 진입.",
        businessRules: [
          "판매 완료된 글은 목록 하단에 흐리게 노출한다.",
          "목록은 최신 등록순으로 정렬한다.",
        ],
        requirementIds: ["req-browse-listing"],
        pageIds: ["page-listing-list", "page-listing-detail"],
        apiIds: ["api-list-listings", "api-get-listing"],
        databaseIds: ["db-listings"],
        requiredData: [],
        optionalData: [],
      },
      {
        id: "feat-listing-chat",
        name: "Listing Chat",
        description: "상세 화면에서 판매자에게 채팅방을 연다.",
        businessRules: [
          "자기 글에는 채팅 버튼을 노출하지 않는다.",
          "채팅방이 없으면 새로 만든다.",
        ],
        requirementIds: ["req-browse-listing"],
        pageIds: ["page-listing-detail"],
        apiIds: ["api-open-chat"],
        databaseIds: ["db-listings", "db-chats"],
        requiredData: [],
        optionalData: ["첫 메시지"],
      },
      {
        id: "feat-listing-create",
        name: "Listing Create",
        description: "새 판매 글 등록.",
        businessRules: [
          "제목과 가격은 필수로 입력해야 한다.",
          "가격은 0원 이상만 등록할 수 있다.",
        ],
        requirementIds: ["req-create-listing"],
        pageIds: ["page-listing-create"],
        apiIds: ["api-create-listing"],
        databaseIds: ["db-listings"],
        requiredData: ["제목", "가격"],
        optionalData: ["사진", "설명"],
      },
    ],

    pages: [
      {
        id: "page-listing-list",
        name: "Listing List",
        description: "판매 글 목록과 등록 진입을 보여주는 메인 화면.",
        featureIds: ["feat-listing-browse"],
        wireframeId: "wf-listing-list",
        pageFlowId: "flow-listing-list",
        apiIds: ["api-list-listings"],
        databaseIds: ["db-listings"],
        x: 40,
        y: 40,
        device: "mobile",
      },
      {
        id: "page-listing-detail",
        name: "Listing Detail",
        description: "선택한 판매 글의 상세 정보와 채팅 진입 화면.",
        featureIds: ["feat-listing-browse", "feat-listing-chat"],
        wireframeId: "wf-listing-detail",
        apiIds: ["api-get-listing", "api-open-chat"],
        databaseIds: ["db-listings", "db-chats"],
        x: 460,
        y: 40,
        device: "mobile",
      },
      {
        id: "page-listing-create",
        name: "Listing Create",
        description: "제목·가격·설명을 입력해 판매 글을 등록하는 화면.",
        featureIds: ["feat-listing-create"],
        wireframeId: "wf-listing-create",
        apiIds: ["api-create-listing"],
        databaseIds: ["db-listings"],
        x: 880,
        y: 40,
        device: "mobile",
      },
    ],

    wireframes: [
      {
        id: "wf-listing-list",
        pageId: "page-listing-list",
        uiElementIds: ["el-list-heading", "el-listing-card", "el-create-button"],
      },
      {
        id: "wf-listing-detail",
        pageId: "page-listing-detail",
        uiElementIds: ["el-detail-title", "el-detail-price", "el-detail-desc", "el-chat-button"],
      },
      {
        id: "wf-listing-create",
        pageId: "page-listing-create",
        uiElementIds: ["el-create-title-input", "el-create-price-input", "el-create-desc", "el-submit-listing"],
      },
    ],

    uiElements: [
      {
        id: "el-list-heading",
        name: "List Heading",
        description: "목록 화면 제목 — 장식 요소.",
        type: "heading",
        props: { text: "우리 동네 중고거래" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-listing-card",
        name: "Listing Card",
        description: "판매 글 한 건. 누르면 상세로 이동한다.",
        type: "text",
        props: { text: "거의 새 자전거 · 80,000원" },
        states: [
          { label: "Default" },
          { label: "Disabled", detail: "판매 완료 글은 흐리게" },
        ],
        action: "Click",
        apiIds: ["api-list-listings"],
        databaseIds: ["db-listings"],
        result: { kind: "navigate", toPageId: "page-listing-detail", detail: "선택한 글 상세로 이동" },
      },
      {
        id: "el-create-button",
        name: "Create Entry Button",
        description: "판매 글 등록 화면으로 이동한다.",
        type: "button",
        props: { label: "물건 등록하기", variant: "solid" },
        states: [{ label: "Default" }],
        action: "Click",
        apiIds: [],
        databaseIds: [],
        result: { kind: "navigate", toPageId: "page-listing-create", detail: "등록 화면으로 이동" },
      },
      {
        id: "el-detail-title",
        name: "Detail Title",
        description: "판매 글 제목 표시.",
        type: "heading",
        props: { text: "거의 새 자전거" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: ["api-get-listing"],
        databaseIds: ["db-listings"],
        result: { kind: "none" },
      },
      {
        id: "el-detail-price",
        name: "Detail Price",
        description: "판매 가격 표시 — 장식 요소.",
        type: "badge",
        props: { text: "80,000원", status: "neutral" },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-detail-desc",
        name: "Detail Description",
        description: "판매 글 설명 본문 — 장식 요소.",
        type: "text",
        props: { text: "1년 사용한 로드 자전거예요. 직거래만 가능해요." },
        states: [{ label: "Default" }],
        action: "",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-chat-button",
        name: "Chat Button",
        description: "판매자와의 채팅방을 연다.",
        type: "button",
        props: { label: "채팅하기", variant: "primary" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "채팅방 여는 중" },
          { label: "Disabled", detail: "자기 글일 때" },
        ],
        action: "Click",
        apiIds: ["api-open-chat"],
        databaseIds: ["db-chats"],
        result: { kind: "toast", detail: "채팅방을 열었어요 안내 노출" },
      },
      {
        id: "el-create-title-input",
        name: "Title Input",
        description: "판매 글 제목을 입력받는다.",
        type: "text-input",
        props: { label: "제목", placeholder: "상품명을 입력하세요" },
        states: [
          { label: "Default" },
          { label: "Error", detail: "제목이 비었을 때" },
        ],
        action: "Input",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-create-price-input",
        name: "Price Stepper",
        description: "판매 가격을 입력받는다.",
        type: "number-stepper",
        props: { value: 0 },
        states: [
          { label: "Default" },
          { label: "Error", detail: "0원 미만일 때" },
        ],
        action: "Change",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-create-desc",
        name: "Description Textarea",
        description: "상품 설명을 입력받는다.",
        type: "textarea",
        props: { label: "설명", placeholder: "상품 상태를 적어주세요" },
        states: [{ label: "Default" }],
        action: "Input",
        apiIds: [],
        databaseIds: [],
        result: { kind: "none" },
      },
      {
        id: "el-submit-listing",
        name: "Submit Listing Button",
        description: "입력값으로 판매 글을 등록하고 목록으로 돌아간다.",
        type: "button",
        props: { label: "등록하기", variant: "solid" },
        states: [
          { label: "Default" },
          { label: "Loading", detail: "등록 중 비활성" },
          { label: "Disabled", detail: "제목·가격 미입력 시" },
        ],
        action: "Click",
        apiIds: ["api-create-listing"],
        databaseIds: ["db-listings"],
        result: { kind: "navigate", toPageId: "page-listing-list", detail: "등록 성공 시 목록으로" },
      },
    ],

    apis: [
      {
        id: "api-list-listings",
        method: "GET",
        path: "/listings",
        purpose: "판매 글 목록을 최신순으로 조회한다.",
        databaseIds: ["db-listings"],
        success: "Listing List Returned",
        error: "조회 실패 — 일시적인 오류 안내",
      },
      {
        id: "api-get-listing",
        method: "GET",
        path: "/listings/:id",
        purpose: "선택한 판매 글의 상세 정보를 조회한다.",
        databaseIds: ["db-listings"],
        success: "Listing Detail Returned",
        error: "글 없음 — 삭제된 글 안내",
      },
      {
        id: "api-open-chat",
        method: "POST",
        path: "/chats",
        purpose: "판매자와의 채팅방을 만들거나 기존 방을 연다.",
        databaseIds: ["db-chats", "db-listings"],
        success: "Chat Room Opened",
        error: "생성 실패 — 잠시 후 다시 시도 안내",
      },
      {
        id: "api-create-listing",
        method: "POST",
        path: "/listings",
        purpose: "새 판매 글을 등록한다.",
        databaseIds: ["db-listings"],
        success: "Listing Created",
        error: "필수값 누락 — 인라인 에러 노출",
      },
    ],

    databases: [
      {
        id: "db-listings",
        name: "listings",
        purpose: "판매 글 저장.",
        columns: [
          "title — 상품 제목",
          "price — 판매 가격",
          "description — 상품 설명",
          "status — 판매중·판매완료 상태",
          "created_at — 등록 시각",
        ],
      },
      {
        id: "db-chats",
        name: "chats",
        purpose: "구매자·판매자 채팅방 저장.",
        columns: [
          "listing_id — 대상 판매 글",
          "buyer_id — 구매 문의자",
          "seller_id — 판매자",
        ],
      },
    ],

    pageFlows: [
      {
        id: "flow-listing-list",
        pageId: "page-listing-list",
        steps: [
          { id: "step-browse-enter", label: "목록 화면 진입", nextStepIds: ["step-browse-pick"] },
          { id: "step-browse-pick", label: "글 선택 또는 등록 진입", nextStepIds: ["step-browse-navigate"] },
          { id: "step-browse-navigate", label: "상세 또는 등록 화면으로 이동", nextStepIds: [] },
        ],
      },
    ],

    userFlow: {
      id: "userflow-market",
      edges: [
        {
          id: "edge-card-to-detail",
          fromPageId: "page-listing-list",
          toPageId: "page-listing-detail",
          triggerElementId: "el-listing-card",
          condition: "판매 글을 선택할 때",
        },
        {
          id: "edge-list-to-create",
          fromPageId: "page-listing-list",
          toPageId: "page-listing-create",
          triggerElementId: "el-create-button",
          condition: "물건 등록을 누를 때",
        },
        {
          id: "edge-create-to-list",
          fromPageId: "page-listing-create",
          toPageId: "page-listing-list",
          triggerElementId: "el-submit-listing",
          condition: "등록 성공 시",
        },
      ],
    },
  },
}
